# game settings 
import math
RES = WIDTH, HEIGHT = 1900, 1000
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2
FPS = 60
PLAYER_SIZE_SCALE = 60

PLAYER_POS = 1.5, 5 #mini map
PLAYER_ANGLE = 0 #góc ban đầu của người chơi
PLAYER_SPEED = 0.0035999 #tốc độ của người chơi
PLAYER_ROT_SPEED = 0.001 / 1000000000 #tốc độ quay xoay góc của người chơi

MOUSE_SENSITIVITY = 0.001 / 5
MOUSE_MAX_REL = 40
MOUSE_BORDER_LEFT = 100
MOUSE_BORDER_RIGHT = WIDTH - MOUSE_BORDER_LEFT

FLOOR_COLOR = (30, 30, 30)

FOV = math.pi / 2
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2 # số lượng tia bắn ra
HALF_NUM_RAYS = NUM_RAYS + 1000 // 2
DELTA_ANGLE = FOV / NUM_RAYS 
MAX_DEPTH = 20

HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2

SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS #độ rộng của mini rect

TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2



